spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: healthyeats-mealservice
          uri: lb:// healthyeats-mealservice

          predicates:
            - Path=/meals/**
          filters:
            - RewritePath=/meals/(?<path>.*), /$\{path}


server:
  port: 8072