spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: HEALTHYEATS-MEALSERVICE
          uri: lb://HEALTHYEATS-MEALSERVICE
          predicates:
            - Path=/meals/**
          filters:
            - RewritePath=/meals/(?<path>.*), /$\{path}

        - id: HEALTHYEATS-USERSERVICE
          uri: lb://HEALTHYEATS-USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}


server:
  port: 8072